# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build deall-technical-test`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t deall-technical-test`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system deall-technical-test && \
          adduser --system -G deall-technical-test deall-technical-test

COPY dist/deall-technical-test deall-technical-test
RUN chown -R deall-technical-test:deall-technical-test .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix deall-technical-test --omit=dev -f install

CMD [ "node", "deall-technical-test" ]
